### ISSUE TITLE
Replace moment with a custom date formatter helper

### ISSUE THREAD

**Issue by ivanvanderbyl** [ivanvanderbyl/ember-hackernews-pwa#3]
To help reduce the bundle size, It'd be good to remove moment because we only use one helper out of that package. Perhaps we could use https://github.com/oskarrough/ember-date-fns or cherry pick something out of there.

**Comment by kiwi-josh** [comment]
I believe that this can be closed now? (https://github.com/ivanvanderbyl/ember-hackernews-pwa/commit/c99c269d7b8098c1f878951a95e7b7bcf9212a93)
